FROM nginx:alpine
COPY /css /usr/share/nginx/html/css
COPY /images /usr/share/nginx/html/images
COPY /js /usr/share/nginx/html/js
COPY /nginx/conf/default.conf /etc/nginx/conf/default.conf
COPY index.html /usr/share/nginx/html/index.html