FROM nginx:alpine
COPY /css /usr/share/nginx/html/css
COPY /images /usr/share/nginx//images
COPY /js /usr/share/nginx/html/js
COPY index.html /usr/share/nginx/html/index.html
COPY default.conf /etc/nginx/conf/default.conf